### ISSUE TITLE
Issues with LDlink Server

### ISSUE THREAD

**Issue by xiaoweizouren** [CBIIT/LDlinkR#36]
Dear LDlink Support Team,

I hope this message finds you well.

I am writing to report a persistent issue I have been encountering while using the LDlink services. Recently, I have repeatedly encountered an "Internal Server Error" message when attempting to use the platform for SNP proxy searches. 

Given the crucial role LDlink plays in my research, I would greatly appreciate any updates regarding the resolution of this issue.

Thank you for your attention to this matter. I look forward to your prompt response and resolution of this issue.

Best regards

**Comment by timyers** [comment]
Hello,

Thank you for your interest in LDlink/LDlinkR.  Are you still encountering an issue?  I just tried a quick test that was successful.

> LDproxy("rs456", c("YRI", "CEU"), "r2", token = Sys.getenv("LDLINK_TOKEN"))

If you are still encountering an "Internal Server Error", could you share the code you're using?  

Kind regards,
Tim

**Comment by xiaoweizouren** [comment]
Hello,

I'm very glad that you took the time to answer my question. I have tried so many times like this “d <- LDproxy("rs34596921","CEU","r2", token = Sys.getenv("9xxxxxxxab32xf"))”, but it did'nt work! It's always showing like this, ” LDlink server is working...”.  But never moving to the next step.

I have also tried it on the web: https://ldlink.nih.gov/.   the LD tools. But after running for a very long time, it showed: Internal server error. Please contact LDlink admin. Was that only I was like this, or was it the cause of the server or workstation crash?

Thank you for your attention to this matter. I'm looking forward to your reply and resolution of this issue.

Best regards

**Comment by timyers** [comment]
Hello again,

Thank you for providing the variant and code examples.  Yes, I too am receiving an error with your code:

"LDlink server is working...

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached [ldlink.nih.gov]: Operation too slow. Less than 1 bytes/sec transferred the last 600 seconds"

But when I use my variant, rs456, it works.  LDlink/LDlinkR is timing out while attempting to calculate proxies for your variant of interest.  I'll contact the LDlink admin on your behalf for additional advice.

Kind regards

**Comment by msbrasher** [comment]
Hello, 

I am having similar issues using LDlinkR through the locuszoomr package. I have had issues with these SNPs so far: chrX:114851730, chrX:132473733, chrX:118817704, chrX:53077683, chrX:155169752, but the same SNPs don't seem to fail each time I try. They all produce the same error Tim mentioned above: 

```
chrX:114851730, chromosome X, position 114351730 to 115351730
973 SNPs/datapoints
Error in curl::curl_fetch_memory(url, handle = handle)
Timeout was reached [ldlink.nih.gov]: Operation too slow. Less than 1 bytes/sec transferred the last 600 seconds
Matched 0 SNPs (10 mins)
```

I was wondering if this was a known issue with the server or API access, and I would like to be included if any resolution has been found. 

Thank you in advance, 

Maizy

**Comment by lgarvert** [comment]
Hello, 

I am encountering the same problem when trying to use LDproxy_batch() with this code:
LDproxy_batch(tmp_snps, 
                    pop = "CEU",  r2d = "r2",  token="0xxxxxxxxa",   append = TRUE,
                    genome_build = "grch37",   win_size = 250000   )

I used the same code with the exact same SNP-set before and it always worked fine.
But since the end of last week, I run into the same issue as described above.  It shows "LDlink server is working...”. But never moves to the next step. 

Best,
Linda

**Comment by timyers** [comment]
Hello all,

Thank you all for posting your issues.  This has helped us identify an issue.  In fact, there have been many users report problems recently, all of you here and LDlink users via other platforms.  Our IT team is actively investigating the cause.  We apologize for the inconvenience and disruption to your research.  Please stay tuned.  I'll post a message here when we have a resolution.

Kind regards,
Tim

**Comment by timyers** [comment]
Hello,

Again, we sincerely apologize for the inconvenience.  The issue has now been resolved and the system is fully operational. 
The problem was due to an unprecedented spike in request volumes which temporarily affected the system's ability to process API requests as expected.  We appreciate your patience and understanding as our team worked to resolve the problem.  If you encounter any further issues, please don't hesitate to contact us.

Best,
Tim

**Comment by xiaoweizouren** [comment]
Dear Tim,



Very sorry to bother you again! After i fist sent the email to you, I found it worked for a fixed time. For me, it is 7:00 to 8:30. After that , the issue happened again!
 
&nbsp;
 
I am very appreciated the work, you and your team did. I know it is not appropriate to bother you again. But I think I should give the message to you maybe it can promote the resolution of this issue.&nbsp;



Best,
Xiaowei


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CBIIT/LDlinkR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月18日(星期三) 凌晨2:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [CBIIT/LDlinkR] Issues with LDlink Server (Issue #36)





 
Hello,
 
Again, we sincerely apologize for the inconvenience.  The issue has now been resolved and the system is fully operational.
 The problem was due to an unprecedented spike in request volumes which temporarily affected the system's ability to process API requests as expected.  We appreciate your patience and understanding as our team worked to resolve the problem.  If you encounter any further issues, please don't hesitate to contact us.
 
Best,
 Tim

**Comment by xiaoweizouren** [comment]
But today it doesn't work even in the fixed time😅

**Comment by timyers** [comment]
Thank you for bringing this to the attention of the LDlink team.  The IT team had a meeting late yesterday to discuss this issue that continues to persist.  I've not heard anything yet but will post here as soon as I learn anything about it.

Again, our apologies for the inconvenience and disruption to your research.

Best,
Tim

**Comment by timyers** [comment]
Ok, thank you for your patience.  I just got word that the issue with the LDlink server should be resolved.  However, please let us know here if you experience otherwise.  Thank you to all!

Tim

**Comment by zealjinwala** [comment]
Hello, 

I have been running into the same issue for the past couple days. I am specifically only using LDmatrix(), and it seems to run into either a Timeout error or a concurrent requests error even when I submit only a single request. Thank you for your attention to this matter. I look forward to your response. 

Thanks,
Zeal

**Comment by timyers** [comment]
Hi Zeal,

Thanks for reaching out.  Are you still experiencing an issue?  If you are, could you share the code?  The following is currently working for me with no issues:

> LDmatrix(c("rs3", "rs4", "rs148890987"),
                    "YRI", "r2",
                     token = Sys.getenv("LDLINK_TOKEN")
                   )

Best,
Tim

**Comment by zealjinwala** [comment]
Hi Tim,

Thank you for your prompt response. Yes, I am still experiencing this error, but I am using a larger list of SNPs (~2500). Here’s the error message: Error in LDmatrix(t$indexSNP, pop = "EUR", r2d = "r2", token = "ee9b835f0fa6",  :
  Gateway Timeout (HTTP 504).

Best,
Zeal
From: Tim Myers ***@***.***>
Date: Tuesday, January 28, 2025 at 10:01 AM
To: CBIIT/LDlinkR ***@***.***>
Cc: Jinwala, Zeal ***@***.***>, Comment ***@***.***>
Subject: [External] Re: [CBIIT/LDlinkR] Issues with LDlink Server (Issue #36)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi Zeal,

Thanks for reaching out. Are you still experiencing an issue? If you are, could you share the code? The following is currently working for me with no issues:

LDmatrix(c("rs3", "rs4", "rs148890987"),
"YRI", "r2",
token = Sys.getenv("LDLINK_TOKEN")
)

Best,
Tim

**Comment by timyers** [comment]
Hi again Zeal,
A team member checked the server and everthing looks good on our end.  It seems the issue is that the time to process the ~2500 SNPs is taking longer than 15 minutes and causing the timeout.  Would it be possible for you to split the list into smaller parts?  If that's not an option, you could send the list of SNPs to us directly with desired LDmatrix parameters.  A member of our team will run it on a local machine for you that doesn't have the 15-minute restriction.  Let us know.
Best,
Tim
